# Generated by Django 4.2.3 on 2023-10-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_student_delete_loginrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
